### ISSUE TITLE
Certain posts from external instances aren't displayed

### ISSUE THREAD

**Issue by ForNeVeR** [dotnet-social/community#4]
I am still new to Mastodon, so please forgive me if I misunderstand something.

I am following this guy, @Minoru: https://functional.cafe/@minoru

You can see that he has plenty of posts visible on his native Mastodon instance.

But when I visit https://dotnet.social/@minoru@functional.cafe, then there's almost nothing, one post from 12'th of Dec and that's it.

What's the reason for this?

**Comment by tbolon** [comment]
Do you have an account on dotnet.social where you follow this account? Because unless someone on the server subscribed to his account, messages are not forwarded to the instance.

**Comment by tbolon** [comment]
When I click on the followers link on his profile on dotnet.social it seems that no one is following him from dotnet.social: https://dotnet.social/@minoru@functional.cafe/followers

Can you give me a link to your account?

**Comment by ForNeVeR** [comment]
Sure thing, I'm sorry I didn't provide the link in the first place. My account is https://dotnet.social/@fornever

**Comment by ForNeVeR** [comment]
Interestingly, the said followers page is empty for me, even though it should mention myself:
<img width="538" alt="image" src="https://user-images.githubusercontent.com/92793/209013093-907a807d-6a1b-4ee0-bea6-951d49e4825d.png">

**Comment by tbolon** [comment]
That's what I find strange... Could you try to unfollow and follow back?

**Comment by tbolon** [comment]
I tried following him, I also found this:  https://functional.cafe/@minoru/106354715543724537

**Comment by ForNeVeR** [comment]
Unfollow, refresh the page.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/92793/209014059-fb108f24-4c26-48ea-9037-1f7016364e96.png">
Follow, refresh the page:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/92793/209014109-020c635d-92c0-4860-acbb-99a597bf017e.png">

…and now it seems I can see a bit more posts: the mentioned from 12th of Dec, and more of older ones.

No new posts still :(

Maybe I have to wait a bit for the sync to kick in?

**Comment by ForNeVeR** [comment]
> I tried following him, I also found this: https://functional.cafe/@minoru/106354715543724537

Sure, I've seen that. But if there are some sync issues for bigger posts, then I assume either nothing would be synced, or some longer posts would be lost.

In this case, though, the only fresh post I see is the one from 12th of Dec, and nothing else, even smaller posts aren't visible.

Say, this one is pretty small: https://functional.cafe/@minoru/109547903827029507

**Comment by tbolon** [comment]
Yes, I edited my comment after I seen that there are recent short posts.

I will check tomorrow, it seems I have a backend log with the status of the synchronization for the server and/or account.

**Comment by tbolon** [comment]
https://functional.cafe/@minoru/followers strange thing also is that the followers list is also empty when I browse his profile on functional.cafe server...

**Comment by tbolon** [comment]
@SparkDustJoe I don't think there is a surge in disk usage. The growth is constant since we started the server one month ago, and the external activity only cause a temporary increase in disk usage, since all cached medias are removed after 7 days.

I tried comparing with another profile from functional.cafe:

* local feed: https://dotnet.social/@robertpi@functional.cafe
* original feed: https://functional.cafe/@robertpi

I don't see any posts missing (the followers/following list is still hidden, or missing in our local profile).

**Comment by Minoru** [comment]
> You can see that he has plenty of posts visible on his native Mastodon instance. But when I visit https://dotnet.social/@minoru@functional.cafe, then there's almost nothing, one post from 12'th of Dec and that's it.

@tbolon already told you that in https://github.com/dotnet-social/community/issues/4#issuecomment-1362068803, but I'm gonna expand it a bit.

This is normal. When you open a user's profile in your instance's UI (or your mobile app), an HTTP request is made to fetch info about their profile (try `curl -H 'Accept: application/activity+json' https://functional.cafe/users/minoru`). This info contains stuff like display name, avatar, and bio, but does *not* include recent posts.

Sometimes that'd be the end of it, and you'd see something like this:
![Screenshot 2022-12-23 at 21-49-06 Functional Café](https://user-images.githubusercontent.com/118875/209393846-b0bc411c-6562-406e-811e-301ea6c6335f.png)

Other times your instance will still display *some* posts. This happens because these posts reached the instance some other way, e.g. because someone from your instance is/was subscribed to that user, or because someone from your instance is/was subscribed to someone who boosted that post.

This behaviour is a long-standing issue in Mastodon: https://github.com/mastodon/mastodon/issues/34 To my knowledge, other Fediverse software (e.g. Pleroma) has the same limitations.

> https://functional.cafe/@minoru/followers strange thing also is that the followers list is also empty when I browse his profile on functional.cafe server...

I have "Hide your social graph" enabled (Mastodon UI: App Settings → User Preferences → Profile). This is orthogonal to hiding follower count which was mentioned [here](https://mastodon.social/@bitbonk/109559753917496976), and which I do *not* have enabled.

**Comment by ForNeVeR** [comment]
Thanks for your clarification, everyone!

I can conclude the following.
1. The posts only started being auto-imported after someone from the server started following the account in question, that's a major downside, but it looks like a design problem of Mastodon. Maybe it will be resolved one day; anyway, we can't do anything about it right now.
2. The followers being inaccessible is not a bug, but a feature of that instance.

Also, it looks like I can see newer posts from @Minoru, so it really works as described.

Case closed, I am sorry for wasting everyone's time on this.
